### ISSUE TITLE
Old and unsupported discord.js

### ISSUE THREAD

**Issue by KM127PL** [KM127PL/KBot#1]
KBot uses an **old** (^12.5.3) version of discord.js, a long time has passed since that and now we have to use modern stuff *ugh*, like version 13, the problem with that is, a lot of breaking changes since then.

Updating discord.js has its pros and cons
Pros:
- Slash commands,
- Integration with threads,
- Integration with [time-outs](https://support.discord.com/hc/en/articles/4413305239191-Time-Out-FAQ)

Cons:
- A lot of stuff has to be rewritten, (this was due to [happen](https://github.com/KM127PL/KBot/blob/main/commands/prefix.js) anyways)
- It seems that a lot of stuff has now been replaced with interactions, what are those?

**Comment by playsenge** [comment]
KM127PL uses an old (^0iq) version of intelligence, a long time has passed since he has blocked me and now we have to live without him _ugh_, like version 1iq, the problem with that is, he is not smart enough to install it.

Updating intelligence has its pros and cons
Pros:

- not mean anymore
- would get only benefits from it
- integration with the planet

Cons:

- ruining own ego
- not wanting to admit own mistake

**Comment by KM127PL** [comment]
As of January 1st 2022 all packages using KM127PL with a version >=0iq must be updated to the 1.2.1-LOLNO version due to a recent hot-fix that applies to all `states` in the `mind.tsx` enum.
Updating does require a bunch of core changes in the orientation of the project.
